// Code generated by protoc-gen-go. DO NOT EDIT.
// source: produto/produto.proto

package produto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Produto struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome                 string   `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Done                 bool     `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Produto) Reset()         { *m = Produto{} }
func (m *Produto) String() string { return proto.CompactTextString(m) }
func (*Produto) ProtoMessage()    {}
func (*Produto) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbfd443cf5fc4c2, []int{0}
}

func (m *Produto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Produto.Unmarshal(m, b)
}
func (m *Produto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Produto.Marshal(b, m, deterministic)
}
func (m *Produto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Produto.Merge(m, src)
}
func (m *Produto) XXX_Size() int {
	return xxx_messageInfo_Produto.Size(m)
}
func (m *Produto) XXX_DiscardUnknown() {
	xxx_messageInfo_Produto.DiscardUnknown(m)
}

var xxx_messageInfo_Produto proto.InternalMessageInfo

func (m *Produto) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Produto) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func (m *Produto) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func init() {
	proto.RegisterType((*Produto)(nil), "produto.Produto")
}

func init() { proto.RegisterFile("produto/produto.proto", fileDescriptor_afbfd443cf5fc4c2) }

var fileDescriptor_afbfd443cf5fc4c2 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x4f,
	0x29, 0x2d, 0xc9, 0xd7, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x92, 0x23, 0x17, 0x7b, 0x00, 0x84, 0x29, 0xc4, 0xc7, 0xc5, 0xe4, 0xe9, 0x22, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x1c, 0xc4, 0xe4, 0xe9, 0x22, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x9f, 0x9b, 0x2a, 0xc1,
	0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x83, 0xc4, 0x52, 0xf2, 0xf3, 0x52, 0x25, 0x98, 0x15,
	0x18, 0x35, 0x38, 0x82, 0xc0, 0xec, 0x24, 0x36, 0xb0, 0x91, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa9, 0x56, 0xed, 0x38, 0x6b, 0x00, 0x00, 0x00,
}
